= 2073

Året är 2073 människan lever i små grupper som så många gånger tidigare i historien.
Denna gången är det inte av tvång för att överleva.
De blivit placerade där av förtegen som styr vardagen, den egna vilja har mer eller mindre reducerats till noll.
Detta har skett med hjälp av algoritmer som till en början såg ut att kunna hjälpa mänskligheten.
Algoritmerna var till en början hjälpsamma så var även AI.
Problemet med AI och algoritmerna var att det var så värdefulla för dess ägare att det hela tiden var tvungna att ändra dem så att de skulle kunde generera mer inkomster till företagen.

I en av dessa grupper så börjar man tala om det finns något som gör det möjligt att kunna slå tillbaka mot företagen och deras förtryck över människan.
Även om bara tanken kunde klassas som förräderi.
Vilket i praktiken medförde att de som protesterade blev placerade i fängelse.
En liten grupp människor ha som sitt ändamål är att vrida tillbaka klockan.
Alltför att den gemene människan ska kunna leva sitt eget liv utan att bli övervakad 24-7.
De försök som de tidigare gjort har alla misslyckats.
Vilket har inneburit att övervakningen har istället ökat.